### ISSUE TITLE
XEDITION ul,ol등의 스타일이 사라짐

### ISSUE THREAD

**Issue by fromthere** [xpressengine/xe-core#1468]
``` css
ul,ol{list-style:none}
```

때문에 모든 ul,ol 태그의 스타일이 사라집니다.
