### ISSUE TITLE
위젯 페이지 수정시 ul, ol, select 등 에 margin과 padding

### ISSUE THREAD

**Issue by treasurej** [xpressengine/xe-core#76]
위젯 페이지 수정시에

``` css
.x ul, .x ol{padding: 0; margin: 0 0 10px 25px;}
.x select{padding: 0; height: 26px; line-height: 26px;}
```

이런 값들이 위젯들 내에 있는 css보다 우선권을 가져서 위젯들이 제대로 표현되지 않는 문제 (틀이 저장했을 때와는 달라서 위젯을 맞추기가 어렵습니다.)

위젯 페이지 수정시에 꼭 필요한 padding과 margin이라면 정확히
css class나 id를 지정해서 margin과 padding을 주는 방법이 좋음.
